ACME: added "acme" directive and client variables to stream.
This patch introduces a new ngx_stream_acme_module, which implements
the "acme" directive and the "$acme_cert_*" and "$acme_cert_key_*"
variables in the "stream" context, mirroring the functionality
available in the "http" context.

The "acme" directive collects all domains specified in the
"server_name" directives of the enclosing "server" block and adds
them to the certificate request handled by the ACME client referenced
in the directive.

The "$acme_cert_*" and "$acme_cert_key_*" variables provide access to
the contents of the certificate and key files obtained by the
associated ACME client.

Note: If the "acme" directive or its associated variables are used in
the "stream" section, the "stream" section must appear after the "http"
section in the configuration file. This is because
ngx_stream_acme_module relies on definitions from ngx_http_acme_module,
which are only available after the "http" section has been parsed.

diff --git a/auto/modules b/auto/modules
--- a/auto/modules
+++ b/auto/modules
@@ -1319,6 +1319,23 @@ if [ $STREAM != NO ]; then
 
         . auto/module
     fi
+
+    if [ $STREAM_ACME = YES ]; then
+
+        if [ $HTTP_ACME != YES ]; then
+            echo "$0: error: ngx_stream_acme_module requires ngx_http_acme_module"
+            exit 1
+        fi
+
+        ngx_module_name=ngx_stream_acme_module
+        ngx_module_incs=
+        ngx_module_deps=
+        ngx_module_srcs=src/stream/ngx_stream_acme_module.c
+        ngx_module_libs=
+        ngx_module_link=$STREAM_ACME
+
+        . auto/module
+    fi
 fi
 
 
